### ISSUE TITLE
Getting exception while downloading video

### ISSUE THREAD

**Issue by RajKateshiya** [viralvaghela/flutter_insta#3]
**Version: flutter_insta 0.1.0**

I have checkout master branch and run example module for test, while trying to download video then getting exception **Unhandled FormatException**.

More details on the stack trace below:
```
E/flutter (23433): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FormatException: Unexpected character (at character 1)
E/flutter (23433): <!DOCTYPE html>
E/flutter (23433): ^
E/flutter (23433): 
E/flutter (23433): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1394:5)
E/flutter (23433): #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1261:9)
E/flutter (23433): #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:926:22)
E/flutter (23433): #3      _parseJson (dart:convert-patch/convert_patch.dart:31:10)
E/flutter (23433): #4      JsonDecoder.convert (dart:convert/json.dart:505:36)
E/flutter (23433): #5      JsonCodec.decode (dart:convert/json.dart:153:41)
E/flutter (23433): #6      FlutterInsta.downloadReels (package:flutter_insta/flutter_insta.dart:12:21)
E/flutter (23433): <asynchronous suspension>
E/flutter (23433): #7      _HomePageState.download (package:flutter_insta_example/main.dart:223:41)
E/flutter (23433): #8      _HomePageState.ReelPage.<anonymous closure> (package:flutter_insta_example/main.dart:207:13)
E/flutter (23433): #9      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter (23433): #10     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (23433): #11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (23433): #12     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (23433): #13     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (23433): #14     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:254:7)
E/flutter (23433): #15     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (23433): #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (23433): #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (23433): #18     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (23433): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (23433): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (23433): #21     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (23433): #22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (23433): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (23433): #24     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (23433): #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
E/flutter (23433): 

```

**Comment by viralvaghela** [comment]
What type of URL are you writing? there's a little bug you can write this https://www.instagram.com/reel/CDlGkdZgB2y  instead of https://www.instagram.com/reel/CDlGkdZgB2y/?igshid=xx7wpetwoaol

**Comment by RajKateshiya** [comment]
Hey @viralvaghela 
Thanks for your confirmation it is working with URL: https://www.instagram.com/reel/CDlGkdZgB2y.
If you can solve that bug (with URL: https://www.instagram.com/reel/CDlGkdZgB2y/?igshid=xx7wpetwoaol) so it would be great for all.
Thanks.

**Comment by codingstark-dev** [comment]
> What type of URL are you writing? there's a little bug you can write this https://www.instagram.com/reel/CDlGkdZgB2y instead of https://www.instagram.com/reel/CDlGkdZgB2y/?igshid=xx7wpetwoaol

hey bro! i am going to fix this error and please accept my pull request

**Comment by viralvaghela** [comment]
@refoxdev Okay !

**Comment by codingstark-dev** [comment]
> @refoxdev Okay !

Done Bro!  😊
