### ISSUE TITLE
Tried calling: []("shortcode_media")

### ISSUE THREAD

**Issue by MajorAkash106** [viralvaghela/flutter_insta#33]
E/flutter (27171): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter (27171): Receiver: null
E/flutter (27171): Tried calling: []("shortcode_media")
E/flutter (27171): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter (27171): #1      FlutterInsta.downloadReels (package:flutter_insta/flutter_insta.dart:19:33)
E/flutter (27171): <asynchronous suspension>
E/flutter (27171): #2      _HomePageState.downloadReels (package:untitled/main.dart:51:13)
E/flutter (27171): <asynchronous suspension>

**Comment by mini0555555** [comment]
same issue. any solution for that
